### PR TITLE
Create Diganta Dutta - SCILAB

### PR DESCRIPTION
**Pull request by DigantaD**
[6699151136915456_1491207440_Projectproposal2.pdf](https://github.com/saurabhshri/GSoC-2017-Accepted-Proposals/files/998585/6699151136915456_1491207440_Projectproposal2.pdf)

### CODE REVIEW

**Comment by saurabhshri** [comment]
Hey @SithBlitz ! Thanks for your efforts in making this repository. :)

To organize things better, the repository has a certain directory structure which could be located [here](https://github.com/saurabhshri/GSoC-2017-Accepted-Proposals#basic-architecture). 

Please update your PR as per the architecture and instructions listed [here](https://github.com/saurabhshri/GSoC-2017-Accepted-Proposals#how-to-submit-a-proposal).

Once updated, I'll be happy to merge it. :)

Edit : There is already an existing proposal in the repository. You may look into that to see how the files and directories are to be actually laid. In case of any doubt, feel free to comment or raise an issue.

**Comment by DigantaD** [comment]
Sure, I will do it by tomorrow morning because I am outside now

**Comment by saurabhshri** [comment]
@SithBlitz Sure! 👍

**Comment by saurabhshri** [comment]
Hello @DigantaD any updates on this PR?

**Comment by saurabhshri** [comment]
Closing due to inactivity. Feel free to re-open again.

**Pull request closed without merging**
