### PR TITLE
Add my project 

### PR DESCRIPTION
**Pull request by Randl**

### CODE REVIEW

**Comment by saurabhshri** [comment]
Thank you @Randl for helping in creating a centralized repository! It would be awesome if other students upload/link their proposals too. Please spread the word! :)

**Comment by Randl** [comment]
I've sent a mail to mailing list, for what it worth.

**Comment by saurabhshri** [comment]
@Randl Oh! I did not recieve the mail.. maybe the email failed or something?

**Comment by Randl** [comment]
Looks like something went wrong. You're welcome to try by yourself.

**Pull request merged**
