### PR TITLE
Spelling errors are corrected

### PR DESCRIPTION
**Pull request by rewanthtammana**
Minor spellings errors were corrected.

### CODE REVIEW

**Comment by saurabhshri** [comment]
Thanks for the PR @rewanth1997 ! Much appreciated. 

I would love to merge the PR but before that could you please fix back the permissions of the files? The permission have been changed from `rw-r--r--` to `rwxr-xr-x` (indicated by 100644 → 100755). Once fixed, I'll merge it. 

A simple `chmod 644` should be enough.

**Comment by rewanthtammana** [comment]
I guess its fine now @saurabhshri

**Comment by saurabhshri** [comment]
@rewanth1997 Almost. :) The `CCExtractor` directory and it's sub-directories still have modified permissions. You may see the _Changed Files_ tab on Github to see the affected files. The only file that should have change is the one you intend to.

**Comment by saurabhshri** [comment]
@rewanth1997 Merged. Thanks for correcting it. :) Hoping to see students upload their proposals soon. Please spread the word.

**Comment by rewanthtammana** [comment]
Sure @saurabhshri , I will upload my proposal also :) I will be working with Nmap this year.

**Comment by saurabhshri** [comment]
@rewanth1997 That's awesome! Can not wait to read it! :)

**Pull request merged**
